In [1]:
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from finglish import f2p

Loading converters...
Loading persian word list...
Loading dictionary...


## load subtacts.csv and subscription3.csv 

#### load subtact and assin header 

In [2]:
subtacts = pd.read_csv("subtacts.csv", names=["user_id",'group_id',"post"])

In [3]:
subtacts.to_csv("msubtacts.csv", index=False)

In [4]:
msubtacts = pd.read_csv("msubtacts.csv")

In [5]:
msubtacts

user_id    group_id            post
0       806465768  1214462642           ADMIN
1       806465768  1427140891           ADMIN
2        96821350  1086836533   FORMER_MEMBER
3        96821350  1149082499   FORMER_MEMBER
4        96821350  1363005718  CURRENT_MEMBER
...           ...         ...             ...
685611  451603133  1135139610  CURRENT_MEMBER
685612  451603133  1376902893   FORMER_MEMBER
685613  433321059  1139143344   FORMER_MEMBER
685614  433321059  1146690784   FORMER_MEMBER
685615  433321059  1168877387  CURRENT_MEMBER

[685616 rows x 3 columns]

#### load subscription3 and assin header 

In [2]:
subscriptions3 = pd.read_csv("subscriptions3.csv", encoding='utf-8', delimiter="#DELIMITER#", header=None)
subscriptions3.columns=['group_id', "peer_name","about"]
subscriptions3['group_id'] = subscriptions3['group_id'].astype(str).str.replace('-', '')

/home/abolfazl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [3]:
subscriptions3

group_id                                          peer_name  \
0      2078972966                            آموزش مهارت های ارتباطی   
1      2041783709                           مستر کنکور 97(استادمددی)   
2      1876162099                                     ناصر خان حجازی   
3      1854882373                                            Pishgoo   
4      1523892810                                      بازارچه ملکان   
...           ...                                                ...   
29430  1799454871                        ????تورک های جذاب لعنتی????   
29431  1799507214                                             、ARIEL   
29432  1799541728                                        金龙社区（免费查合约）   
29433  1799590600                                         ???? ?????   
29434  1799725737  ??ٌٍٍٍٍٍٍٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜۘۘۘۘ͜͡⚘͜͡...   

                                                   about  
0      سلام .من علیرضا کرمی هستم  مربی و مدرس دوره‌ها...  
1      ? آقای خاص مشاوره و برنامه ریزی کنکور ? ?مبتکر...  
2      تنها کانال فعال تلگرامي یادبودناصرخان حجازی✌✋ ...  
3      ? فال☕دعا\#طلسم\# کارت\#جزوه\#دعا طلسم\#مهره م...  
4      ?سیمساری آنلاین ملکان?                        ...  
...                                                  ...  
29430  ??گپ تورک های جذاب لعنتی???  ??تورک های ارومیه...  
29431  ˓ ??????? ?? ????? ??????? ˒                20...  
29432                                      进群福利免费查bsc合约！  
29433  "Hi ass-kisser @durov,i swear that this channe...  
29434  خوش آمدید به   \#ابر  \#گپ   \#طهران   \#کرج  ...  

[29435 rows x 3 columns]

In [8]:
msubtacts.dtypes

user_id      int64
group_id     int64
post        object
dtype: object

In [4]:
convert_dict = {'group_id': int,
                }

In [5]:
subscriptions3 = subscriptions3.astype(convert_dict)

In [11]:
merged_df = subscriptions3.merge(msubtacts, on="group_id", how='inner')

In [12]:
merged_df

group_id                                          peer_name  \
0       1000006831                                روزنامه وقایع استان   
1       1000027505                                         Cheet Bazi   
2       1000039922                              میلیتــــــــــاریسمـ   
3       1000157416                   EdonTools ( ابزارآلات ادون تولز)   
4       1000170429                                        KHAMENEI.IR   
...            ...                                                ...   
685605  1799725737  ??ٌٍٍٍٍٍٍٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜۘۘۘۘ͜͡⚘͜͡...   
685606  1799725737  ??ٌٍٍٍٍٍٍٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜۘۘۘۘ͜͡⚘͜͡...   
685607  1799725737  ??ٌٍٍٍٍٍٍٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜۘۘۘۘ͜͡⚘͜͡...   
685608  1799725737  ??ٌٍٍٍٍٍٍٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜۘۘۘۘ͜͡⚘͜͡...   
685609  1799725737  ??ٌٍٍٍٍٍٍٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜٜۘۘۘۘ͜͡⚘͜͡...   

                                                    about     user_id  \
0       ?روزنامه صبح"وقایع استان"مرجع رسمی اخبار استان...   173318782   
1       All the content of the channel is sent solely ...   541239771   
2       لینک گروه https://t.me/joinchat/KSVK9-_7yyI2OW...   362541001   
3       مرکز پخش ابزارآلات ادونEDON   صنعتی،کشاورزی و ...   119944726   
4       پايگاه اطلاع رسانی دفترحفظ و نشر آثار حضرت آیت...   152638140   
...                                                   ...         ...   
685605  خوش آمدید به   \#ابر  \#گپ   \#طهران   \#کرج  ...  1194817985   
685606  خوش آمدید به   \#ابر  \#گپ   \#طهران   \#کرج  ...  1444812492   
685607  خوش آمدید به   \#ابر  \#گپ   \#طهران   \#کرج  ...  1771289551   
685608  خوش آمدید به   \#ابر  \#گپ   \#طهران   \#کرج  ...  1503314367   
685609  خوش آمدید به   \#ابر  \#گپ   \#طهران   \#کرج  ...   542906195   

                           post  
0       CHANNEL_EXTRACTRD_ADMIN  
1                CURRENT_MEMBER  
2                CHANNEL_MEMBER  
3       CHANNEL_EXTRACTRD_ADMIN  
4                CHANNEL_MEMBER  
...                         ...  
685605           CURRENT_MEMBER  
685606           CURRENT_MEMBER  
685607           CURRENT_MEMBER  
685608           CURRENT_MEMBER  
685609           CURRENT_MEMBER  

[685610 rows x 5 columns]

In [13]:
merged_df['peer_name'] = merged_df['peer_name'].str.replace('?', '')
merged_df['about'] = merged_df['about'].str.replace('?', '')
merged_df['peer_name'] = merged_df['peer_name'].str.replace('#', '')
merged_df['about'] = merged_df['about'].str.replace('#', '')
merged_df['peer_name'] = merged_df['peer_name'].str.replace("\\","")
merged_df['about'] = merged_df['about'].str.replace('\\', '')

/var/folders/7y/lh6z9mgj7w190j6vw0pfrdbm0000gn/T/ipykernel_6177/3869576289.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  merged_df['peer_name'] = merged_df['peer_name'].str.replace('?', '')
/var/folders/7y/lh6z9mgj7w190j6vw0pfrdbm0000gn/T/ipykernel_6177/3869576289.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  merged_df['about'] = merged_df['about'].str.replace('?', '')
/var/folders/7y/lh6z9mgj7w190j6vw0pfrdbm0000gn/T/ipykernel_6177/3869576289.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  merged_df['peer

In [14]:
merged_df.to_csv("merged_df.csv", index=False)

In [6]:
sub_merged = subscriptions3.iloc[:100]

In [7]:
sub_merged

group_id                 peer_name  \
0   2078972966   آموزش مهارت های ارتباطی   
1   2041783709  مستر کنکور 97(استادمددی)   
2   1876162099            ناصر خان حجازی   
3   1854882373                   Pishgoo   
4   1523892810             بازارچه ملکان   
..         ...                       ...   
95  1002265355       گروه عمران و معماری   
96  1002272868                    یزدرسا   
97  1002292300                     Tripp   
98  1002307702                 توییت فان   
99  1002354639           ?chaarghad_com?   

                                                about  
0   سلام .من علیرضا کرمی هستم  مربی و مدرس دوره‌ها...  
1   ? آقای خاص مشاوره و برنامه ریزی کنکور ? ?مبتکر...  
2   تنها کانال فعال تلگرامي یادبودناصرخان حجازی✌✋ ...  
3   ? فال☕دعا\#طلسم\# کارت\#جزوه\#دعا طلسم\#مهره م...  
4   ?سیمساری آنلاین ملکان?                        ...  
..                                                ...  
95  کانال های ما  @Fazee2 @HiAzmoon @Moghararat22 ...  
96  شهروند خبرنگار و ارسال محتوا:           @Erteb...  
97         Get High   Admin tabadol: @dark_than_black  
98  مجله توییت فان ?فعالیت کانال توییت فان به دور ...  
99  روسری ترکمنی ? طرح های کمیاب اصیل?    شماره تم...  

[100 rows x 3 columns]

In [8]:
def convert_pinglish_to_persian(text):
    if isinstance(text, str) and any(char.isalpha() for char in text):
        return f2p(text)
    return text


In [9]:
# Assuming your DataFrame is named "df"
sub_merged['persion'] = sub_merged['peer_name'].apply(convert_pinglish_to_persian)


/home/abolfazl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [11]:
sub = subscriptions3.iloc[100:200]

In [12]:
sub['persion'] = sub['peer_name'].apply(convert_pinglish_to_persian)


/home/abolfazl/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [13]:
contains_english = subscriptions3["peer_name"].str.contains('[A-Za-z]', na=False)


In [14]:
count_english_rows = contains_english.sum()


In [15]:
count_english_rows

6278

In [17]:
sub

group_id                       peer_name  \
100  1002410325                ?? اشپزی ودسر ??   
101  1002422459                      گلهای بهشت   
102  1002436825                       توفان یزد   
103  1002444037                  ??شاتوتستان ??   
104  1002468486  دکتر پریسا نصری | parisa nasri   
..          ...                             ...   
195  1005155162            تربیت فرزند نورِدیده   
196  1005190203       ?حقایق عجیب و‌ شگفت انگیز   
197  1005228088                 ? آرامش زندگی ?   
198  1005268692             خوراک خام‌گیاهی VEG   
199  1005316016                     Radio Javan   

                                                 about  \
100  گروه آشپزی و دسر ?? لینک گروه:?? https://t.me/...   
101  @golhayebehesht5 ??سفارش تک  مدیر??  @golhaye_...   
102                         راهی برای  ارتباط  @Mshogh   
103                                                NaN   
104  سایت ? https://www.parisanasri.com  دانلود اپل...   
..                                                 ...   
195  پرسش وپاسخ نداریم   تبلیغات @tablighat_128  سف...   
196  مجله علمی وسرگرمی? حقایق عجیب،دانستنیها? اتفاق...   
197                                   مدیریت : @MM9259   
198  گروه خوراک خامگیاهی VEG ویژه قرار دادن غذاهای ...   
199                      Radio Javans Official Channel   

                         persion  
100                   اشپزی ودسر  
101                   گلهای بهشت  
102                    توفان یزد  
103                    شاتوتستان  
104  دکتر پریسا نصری پریسا ناصری  
..                           ...  
195         تربیت فرزند نورِدیده  
196     حقایق عجیب و‌ شگفت انگیز  
197                  آرامش زندگی  
198           خوراک خام‌گیاهی وگ  
199                   رادیو جوان  

[100 rows x 4 columns]

In [16]:
from preprocess import clean_up_pipeline
bow_names = []
bow_abouts = []
bow = []

for i, row in sub.iterrows():
    name = clean_up_pipeline(row["persion"])
    about = clean_up_pipeline(row["about"])
    bow_names += [name]
    bow_abouts += [about]
    bow += [name + ' ' + about]
sub['bow_name'] = bow_names
sub['bow_about'] = bow_abouts
sub['bow'] = bow

TypeError: expected string or bytes-like object

In [36]:
sub

group_id                                peer_name  \
100  1000470102              ENGLISH TRAINING GROUP (RM)   
101  1000470102              ENGLISH TRAINING GROUP (RM)   
102  1000470102              ENGLISH TRAINING GROUP (RM)   
103  1000470102              ENGLISH TRAINING GROUP (RM)   
104  1000470102              ENGLISH TRAINING GROUP (RM)   
..          ...                                      ...   
195  1000745092  گروه تخصصی پرستاری/مامایی/پزشکی دربالین   
196  1000745092  گروه تخصصی پرستاری/مامایی/پزشکی دربالین   
197  1000745092  گروه تخصصی پرستاری/مامایی/پزشکی دربالین   
198  1000745092  گروه تخصصی پرستاری/مامایی/پزشکی دربالین   
199  1000745092  گروه تخصصی پرستاری/مامایی/پزشکی دربالین   

                                                 about     user_id  \
100  Our GROUP LINK    https://t.me/joinchat/DeF5xj...   465148562   
101  Our GROUP LINK    https://t.me/joinchat/DeF5xj...   122450098   
102  Our GROUP LINK    https://t.me/joinchat/DeF5xj...   207084440   
103  Our GROUP LINK    https://t.me/joinchat/DeF5xj...   136787747   
104  Our GROUP LINK    https://t.me/joinchat/DeF5xj...   255227508   
..                                                 ...         ...   
195       https://t.me/joinchat/BRgrJzumKIQGh24WMWHMpg   470303829   
196       https://t.me/joinchat/BRgrJzumKIQGh24WMWHMpg   370806675   
197       https://t.me/joinchat/BRgrJzumKIQGh24WMWHMpg   410591476   
198       https://t.me/joinchat/BRgrJzumKIQGh24WMWHMpg  1380961791   
199       https://t.me/joinchat/BRgrJzumKIQGh24WMWHMpg   325145466   

               post                                  persion  \
100  CURRENT_MEMBER                   انگلیش ترینینگ گروپ رم   
101  CURRENT_MEMBER                   انگلیش ترینینگ گروپ رم   
102  CURRENT_MEMBER                   انگلیش ترینینگ گروپ رم   
103  CURRENT_MEMBER                   انگلیش ترینینگ گروپ رم   
104   FORMER_MEMBER                   انگلیش ترینینگ گروپ رم   
..              ...                                      ...   
195   FORMER_MEMBER  گروه تخصصی پرستاری مامایی پزشکی دربالین   
196   FORMER_MEMBER  گروه تخصصی پرستاری مامایی پزشکی دربالین   
197   FORMER_MEMBER  گروه تخصصی پرستاری مامایی پزشکی دربالین   
198   FORMER_MEMBER  گروه تخصصی پرستاری مامایی پزشکی دربالین   
199   FORMER_MEMBER  گروه تخصصی پرستاری مامایی پزشکی دربالین   

                               bow_name  bow_about  
100                 انگل ترینینگ گروپ ر  اینستاگرا  
101                 انگل ترینینگ گروپ ر  اینستاگرا  
102                 انگل ترینینگ گروپ ر  اینستاگرا  
103                 انگل ترینینگ گروپ ر  اینستاگرا  
104                 انگل ترینینگ گروپ ر  اینستاگرا  
..                                  ...        ...  
195  گروه تخصص پرستار ماما پزشک دربالین             
196  گروه تخصص پرستار ماما پزشک دربالین             
197  گروه تخصص پرستار ماما پزشک دربالین             
198  گروه تخصص پرستار ماما پزشک دربالین             
199  گروه تخصص پرستار ماما پزشک دربالین             

[100 rows x 8 columns]

In [58]:
sub["bow"].tolist()

['انگل ترینینگ گروپ ر اینستاگرا',
 'انگل ترینینگ گروپ ر اینستاگرا',
 'انگل ترینینگ گروپ ر اینستاگرا',
 'انگل ترینینگ گروپ ر اینستاگرا',
 'انگل ترینینگ گروپ ر اینستاگرا',
 'انگل ترینینگ گروپ ر اینستاگرا',
 'اعلام ترانزیت پرشیا مهرو بسم\u200cالله الرحمن الرحیم ارتباط ادمین کانال اعلام',
 'اعلام ترانزیت پرشیا مهرو بسم\u200cالله الرحمن الرحیم ارتباط ادمین کانال اعلام',
 'اعلام ترانزیت پرشیا مهرو بسم\u200cالله الرحمن الرحیم ارتباط ادمین کانال اعلام',
 'تبریز کانال شهر اولین معرف رویداد جاذبه نیازمندی\u200cهای شهر تبریز',
 'باحالترین پست تلگرا جک عاشقانهمد زیبایی سرگرم خبر جهت تبلیغات کانال خوب با دی ارتباط بود#باش تبادل ندار',
 'عشق رهبر سید علی خامنه حفظه الله خون دررگ ماست خامنه رهبر ماست دوستان بزرگوار ادد ربات ممنوع لطفا رعایت',
 'عشق رهبر سید علی خامنه حفظه الله خون دررگ ماست خامنه رهبر ماست دوستان بزرگوار ادد ربات ممنوع لطفا رعایت',
 'عشق رهبر سید علی خامنه حفظه الله خون دررگ ماست خامنه رهبر ماست دوستان بزرگوار ادد ربات ممنوع لطفا رعایت',
 'عشق رهبر سید علی خامنه حفظه الله خون دررگ ما

In [56]:
from collections import Counter
# Sample bag of words
for bag_of_words in sub["bow"].tolist():
    
    # Split the bag of words into individual words
    words = bag_of_words.split(' ')
    # Count word frequencies
    word_counts = Counter(words)

    # Find the word with the highest frequency
    main_word = word_counts.most_common(2)
    print(f"Main word: {main_word}")

Main word: [('انگل', 1), ('ترینینگ', 1)]
Main word: [('انگل', 1), ('ترینینگ', 1)]
Main word: [('انگل', 1), ('ترینینگ', 1)]
Main word: [('انگل', 1), ('ترینینگ', 1)]
Main word: [('انگل', 1), ('ترینینگ', 1)]
Main word: [('انگل', 1), ('ترینینگ', 1)]
Main word: [('اعلام', 2), ('ترانزیت', 1)]
Main word: [('اعلام', 2), ('ترانزیت', 1)]
Main word: [('اعلام', 2), ('ترانزیت', 1)]
Main word: [('تبریز', 2), ('شهر', 2)]
Main word: [('باحالترین', 1), ('پست', 1)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('رهبر', 2), ('خامنه', 2)]
Main word: [('لینک', 3), ('کانال', 3)]
Main word: [('لینک', 3), ('کانال', 3)]
Main word: [('لینک', 3), ('کانال', 3)]
Ma

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
bag_of_words = sub["bow"].tolist()
# Create a TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the bag of words data
tfidf_matrix = tfidf_vectorizer.fit_transform(bag_of_words)

# Access the TF-IDF matrix as a NumPy array
tfidf_matrix_array = tfidf_matrix.toarray()

# Print the TF-IDF matrix
print(tfidf_matrix_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
